//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyBots.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robot
    {
        public int RobotId { get; set; }
        public string Name { get; set; }
        public int Speed { get; set; }
        public int Damage { get; set; }
        public int Hitpoints { get; set; }
        public int Energy { get; set; }
        public string Image { get; set; }
    }
}
